### ISSUE TITLE
How should the POST request be made

### ISSUE THREAD

**Issue by ilclaudio** [sbrannstrom/nestjs-passport-ldap-example#15] opened 2022-05-07 16:08 UTC
Hi,
how should the POST request be made?
I'm trying this without success:

`POST http://localhost:3000/ldap`

with body:

```
{
"username": "myname",
"password": "mypassword"
}
```

**Comment by makeappnetworks** [comment] 2023-03-25 19:44
> Hi, how should the POST request be made? I'm trying this without success:
> 
> `POST http://localhost:3000/ldap`
> 
> with body:
> 
> ```
> {
> "username": "myname",
> "password": "mypassword"
> }
> ```

Did you succeed?

**Comment by sbrannstrom** [comment] 2023-03-25 21:20
Hi @ilclaudio and @makeappnetworks. I've updated the repository and improved the example. Check `ldap.strategy.ts` now.

**Comment by sbrannstrom** [comment] 2023-03-25 21:23
Closing this as the example has been updated and is working as intended.

**Closed by sbrannstrom** 2023-03-25 21:23 UTC
